### ISSUE TITLE
No source for Alestorm Video Game

### ISSUE THREAD

**Issue by JakubFojtik** [Polydus/skypiratesden#1]
The link for source code at https://polydus.com/ale just points to the same page! Is it an oversight or an intention?

**Comment by Polydus** [comment]
@JakubFojtik absolutely an oversight, thank you for reminding me. I'll post it shortly. Just curious, how did you find it? 

edit: It's up here: https://github.com/Polydus/alestorm-video-game

**Comment by JakubFojtik** [comment]
Found it via your comment at the Alestorm's [video](https://www.youtube.com/watch?v=-r8jlHDBMsw) of course :)
Thanks for the source!
